### ISSUE TITLE
Unknown entities in /:owner/:repo/contributors on twitter deployed version

### ISSUE THREAD

**Issue by OrkoHunter** [OSSHealth/augur#147]
Hi!

I have a couple of questions for the API `/:owner/:repo/contributors`.

The API http://twitter.augurlabs.io/api/unstable/twitter/finatra/contributors
returns

```
[{"name":"cacoco","user":7875,"commits":868.0,"issues":5.0,"commit_comments":3.0,"issue_comments":366.0,"pull_requests":0.0,"pull_request_comments":0.0,"total":1242.0},
{"name":"capotej","user":117128,"commits":138.0,"issues":31.0,"commit_comments":0.0,"issue_comments":97.0,"pull_requests":0.0,"pull_request_comments":0.0,"total":266.0},
{"name":"scosenza","user":5101696,"commits":72.0,"issues":8.0,"commit_comments":0.0,"issue_comments":72.0,"pull_requests":0.0,"pull_request_comments":0.0,"total":152.0},
{"name":"QMHGHMYU","user":9640691,"commits":92.0,"issues":0.0,"commit_comments":0.0,"issue_comments":0.0,"pull_requests":0.0,"pull_request_comments":0.0,"total":92.0},
{"name":"QHPUWUNQ","user":14263062,"commits":76.0,"issues":0.0,"commit_comments":0.0,"issue_comments":0.0,"pull_requests":0.0,"pull_request_comments":0.0,"total":76.0},
{"name":"codecov-io","user":5636467,"commits":0.0,"issues":0.0,"commit_comments":0.0,"issue_comments":57.0,"pull_requests":0.0,"pull_request_comments":0.0,"total":57.0},
{"name":"UEKURALX","user":9145111,"commits":45.0,"issues":0.0,"commit_comments":0.0,"issue_comments":0.0,"pull_requests":0.0,"pull_request_comments":0.0,"total":45.0},
{"name":"ryanoneill","user":35556,"commits":5.0,"issues":0.0,"commit_comments":1.0,"issue_comments":39.0,"pull_requests":0.0,"pull_request_comments":0.0,"total":45.0},
...more
```

The result has usernames like `QMHGHMYU`, `QHPUWUNQ`, `UEKURALX`, which do not correspond to any github username. Is this an expected behavior? 

Also, what does the number corresponding to `user` signify?

**Comment by ccarterlandis** [comment]
Hi @OrkoHunter! Thanks for the concern. As far as I can tell, returning those three users (`QMHGHMYU`, `QHPUWUNQ`, `UEKURALX`) is expected behavior. It would appear that those three are "fake" users, as you can see in these screencaps from the GHTorrent database. 

<img width="1256" alt="screen shot 2018-08-14 at 5 16 18 pm" src="https://user-images.githubusercontent.com/31522931/44121712-9c659e80-9fe6-11e8-8a9f-87d6819e4cf1.png">
<img width="1255" alt="screen shot 2018-08-14 at 5 20 32 pm" src="https://user-images.githubusercontent.com/31522931/44121713-9c659e80-9fe6-11e8-9a33-924894ad643a.png">
<img width="1257" alt="screen shot 2018-08-14 at 5 20 50 pm" src="https://user-images.githubusercontent.com/31522931/44121714-9c659e80-9fe6-11e8-986b-1f3906037f02.png">

And as you also might be able to discern from the screencaps, the `user` parameter is that user's ID in the database.

Hope that helps! Let me know if you have any other questions.

**Comment by OrkoHunter** [comment]
Hi @ccarterlandis! Thank you for your quick response. This is helpful.

Self note: http://ghtorrent.org/relational.html about `fake` users.
