### ISSUE TITLE
Reversed trend in /:owner/:repo/timeseries/watchers and possibly incorrect number

### ISSUE THREAD

**Issue by OrkoHunter** [OSSHealth/augur#152]
1. Looking at http://twitter.augurlabs.io/api/unstable/rails/rails/timeseries/watchers I think that the trend of watchers and the dates have been reversed i.e. watchers decrease with time. Maybe it's a bug.

2. After reversing the trend, I believe the number does not relate to the actual number of watchers on `https://github.com/rails/rails`

**Comment by ccarterlandis** [comment]
Hi @OrkoHunter,

`/:owner/:repo/timeseries/watchers` returns only the **new** watchers in that time period, instead of the **total** number of watchers in that time period. This is why the count goes up and down, and why the number =/=  the total number of watchers. If you want, I can look into adding a gross watchers and a net watchers endpoint.

**Comment by OrkoHunter** [comment]
Oh! Thanks @ccarterlandis for telling me about this. I did not expect the `watchers` endpoint to give the difference. Although that is a helpful metric. I wish it remains, but having the trend of the actual number will be helpful as well. (Not urgent in any way).

**Comment by ccarterlandis** [comment]
@OrkoHunter sure thing! If it's okay with you, I'll mark this as closed. If you want to open an issue detailing the new endpoints you'd like to see, that'd be very helpful! If you're busy, I can do it as well.

**Comment by OrkoHunter** [comment]
Sure, this is closed! I will open an issue shortly.

**Comment by OrkoHunter** [comment]
Ref - #153
