### ISSUE TITLE
Ubuntu docker-compose install error 

### ISSUE THREAD

**Issue by amunz** [OSSHealth/augur#80]
Hello,

I have everything set up as per the Docker installation with the environment variables set up, but I am receiving the error: 
`IOError: Can not access file in context: /home/adammunoz/ghdata/docker/static-web/www`
![screen shot 2018-02-16 at 3 07 32 pm](https://user-images.githubusercontent.com/22136995/36329452-99108332-132b-11e8-9a3b-4b4e74cb5bac.jpg)

I do have docker, docker compose and all the other dependencies set up.  
Any assistance would be appreciated. 

Thanks, 
Adam

**Comment by howderek** [comment]
Hi @amunz, as far as I can tell the version of docker-compose.yml in master no longer refers to the Dockerfile that depends on static-web/www. Are you up to date with master?

**Comment by sgoggins** [comment]
@amunz : Please do let us know if its working for you on Ubuntu. We do not yet systematically test the docker image on all versions of Ubuntu, so if we missed something we surely want to address it for you. 

If the issue is resolved, let us know.  If it is not resolved, please let us know. If you do not let us know we will just keep asking. ;)

**Comment by sgoggins** [comment]
fixed!
